name: remitance
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
   sdk: ">=3.5.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  internet_connection_checker: ^3.0.1
  responsive_sizer: ^3.3.1
  dartz: ^0.10.1
  intl: ^0.20.1
  hive: ^2.2.3
 
  hive_flutter: ^1.1.0
  flutter_displaymode: ^0.6.0
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  dio: ^5.8.0+1
  logger: ^2.5.0
  flutter_dotenv: ^5.2.1
  device_info_plus: ^11.3.0
  uuid: ^4.5.1
  gap: ^3.0.1
  flag: ^7.0.0
  local_auth: ^2.3.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  


dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  
  assets:
    - assets/images/
  

 
flutter_launcher_icons:

  image_path: "assets/icons/icon.png"
  android: true 
  ios: true 
  adaptive_icon_foreground: "assets/icons/icon.png"
  adaptive_icon_background: "#FFFFFF"  
  adaptive_icon_background_dark: "#A676B9" 
  adaptive_icon_foreground_inset: 16 
  adaptive_icon_monochrome: "assets/icons/icon.png"
  min_sdk_android: 21
  android_icon_size: 60  
  ios_icon_size: 180
  remove_alpha_ios: true

flutter_native_splash:
  
  android: true
  ios: true
  web: false
  color: "#000000"
  image: assets/icons/icon.png


  android_12:
    color: "#000000"
    image: assets/icons/icon.png
  



